// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicLibraryWebAPI.Data;

#nullable disable

namespace MusicLibraryWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230712153927_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MusicLibraryWebAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "The Arcade",
                            Artist = "Hyper Crush",
                            Genre = "Pop Rap",
                            ReleaseDate = 2008,
                            Title = "Candy Store"
                        },
                        new
                        {
                            Id = 2,
                            Album = "The Arcade",
                            Artist = "Hyper Crush",
                            Genre = "Pop Rap",
                            ReleaseDate = 2008,
                            Title = "Twisted"
                        },
                        new
                        {
                            Id = 3,
                            Album = "The Arcade",
                            Artist = "Hyper Crush",
                            Genre = "Pop Rap",
                            ReleaseDate = 2008,
                            Title = "Boom Box"
                        },
                        new
                        {
                            Id = 4,
                            Album = "The Arcade",
                            Artist = "Hyper Crush",
                            Genre = "Pop Rap",
                            ReleaseDate = 2008,
                            Title = "Disco Tech"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Kings of Crunk",
                            Artist = "Lil Jon",
                            Genre = "Rap",
                            ReleaseDate = 2002,
                            Title = "Get Low"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
